name: 🐞 Bug/Help
description: File a bug/issue
title: "[BUG/Help] <title>"
labels: []
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: | 
      A concise description of what you're experiencing, with screenshot attached if possible.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Python**: 3.8
        - **Transformers**: 4.26.1
        - **PyTorch**: 1.12
        - **CUDA Support**: True
    value: |
        - OS:
        - Python:
        - Transformers:
        - PyTorch:
        - CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
