version: "3"
services:
  stable-diffusion:
    build:
      dockerfile: ./Dockerfile
      context: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    working_dir: /app
    ports:
      - "9000:8000"
    command: bash -c "python web_demo2.py"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
